package cafeteria;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Angel
 */
public class Inventory extends javax.swing.JFrame {

    DefaultListModel model = new DefaultListModel();

    public Inventory() {
        initComponents();
        
        // SE LLAMA AL METODO SETPZAS Y SE LE ASIGNAN VALORES A LOS PARAMETROS
        setPzas(1, pzasCafe);
        setPzas(2, pzasAzucar);
        setPzas(3, pzasLeche);
        setPzas(4, pzasGalleta);
        setPzas(5, pzasPastel);
        setPzas(6, pzasPay);
        setPzas(7, pzasHelado);
        setPzas(8, pzasMuffin);
    }

    // METODO PARA MOSTRAR LA CANTIDAD DISPONIBLE QUE HAY DE INGREDIENTES EN LA BASE DE DATOS
    public void setPzas(int idIngrediente, JLabel label) {
        
        // SE OBTIENE LA CANTIDAD DISPONIBLE DESDE LA BASE DE DATOS Y SE MUESTRA EN El LABEL
        String sql = "SELECT disponible FROM ingrediente WHERE id_ingrediente = " + idIngrediente;
        Connection cn = null;
        PreparedStatement pst = null;
        ResultSet rs = null;

        try {
            cn = DBConexion.conectar();
            pst = cn.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                String registro = rs.getString("disponible");
                label.setText(registro);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al conectar");
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (pst != null) {
                    pst.close();
                }
                if (cn != null) {
                    cn.close();
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }

    // METODO PARA ACTUALIZAR LA CANTIDAD DISPONIBLE AL AGREGAR INVENTARIO EN LA BASE DE DATOS
    public void agregar(int idAdd, String sumTxt) {
        String sql = "UPDATE ingrediente SET disponible = " + sumTxt + " WHERE id_ingrediente = " + idAdd + ";";
        Connection cn = null;
        Statement pst = null;
        int rs = 0;

        try {
            cn = DBConexion.conectar();
            pst = cn.createStatement();
            rs = pst.executeUpdate(sql);

            if (rs == 0) {
                //error
                JOptionPane.showMessageDialog(null, "Error al agregar");
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al conectar");
        } finally {
            try {
                if (pst != null) {
                    pst.close();
                }
                if (cn != null) {
                    cn.close();
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        out = new javax.swing.JButton();
        inv = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        invPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txt1 = new javax.swing.JLabel();
        pzasCafe = new javax.swing.JLabel();
        addCafe = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pzasAzucar = new javax.swing.JLabel();
        addAzucar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pzasLeche = new javax.swing.JLabel();
        addLeche = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pzasGalleta = new javax.swing.JLabel();
        addGalleta = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        pzasPay = new javax.swing.JLabel();
        addPay = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        pzasPastel = new javax.swing.JLabel();
        addPastel = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        pzasHelado = new javax.swing.JLabel();
        addHelado = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        txt2 = new javax.swing.JLabel();
        pzasMuffin = new javax.swing.JLabel();
        addMuffin = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inventario");

        jPanel1.setBackground(new java.awt.Color(88, 36, 23));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cafeteria");

        out.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logout.png"))); // NOI18N
        out.setContentAreaFilled(false);
        out.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(out, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(out, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        inv.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        inv.setText("Inventario");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        txt1.setText("Café");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 23, 0, 0);
        jPanel3.add(txt1, gridBagConstraints);

        pzasCafe.setText("56");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 23, 11, 0);
        jPanel3.add(pzasCafe, gridBagConstraints);

        addCafe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Add.png"))); // NOI18N
        addCafe.setText("Añadir");
        addCafe.setContentAreaFilled(false);
        addCafe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addCafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCafeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 23, 0, 10);
        jPanel3.add(addCafe, gridBagConstraints);

        jLabel5.setText("pzas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 7, 11, 0);
        jPanel3.add(jLabel5, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel3.setText("Azúcar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 23, 0, 0);
        jPanel2.add(jLabel3, gridBagConstraints);

        pzasAzucar.setText("80");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 23, 11, 0);
        jPanel2.add(pzasAzucar, gridBagConstraints);

        addAzucar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Add.png"))); // NOI18N
        addAzucar.setText("Añadir");
        addAzucar.setContentAreaFilled(false);
        addAzucar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addAzucar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAzucarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 23, 0, 10);
        jPanel2.add(addAzucar, gridBagConstraints);

        jLabel6.setText("pzas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 18, 11, 0);
        jPanel2.add(jLabel6, gridBagConstraints);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(199, 88));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel7.setText("Leche");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 23, 0, 0);
        jPanel4.add(jLabel7, gridBagConstraints);

        pzasLeche.setText("58");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 23, 11, 0);
        jPanel4.add(pzasLeche, gridBagConstraints);

        addLeche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Add.png"))); // NOI18N
        addLeche.setText("Añadir");
        addLeche.setContentAreaFilled(false);
        addLeche.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addLeche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLecheActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 25, 0, 10);
        jPanel4.add(addLeche, gridBagConstraints);

        jLabel17.setText("pzas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 2, 11, 0);
        jPanel4.add(jLabel17, gridBagConstraints);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel9.setText("Galletas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 23, 0, 0);
        jPanel5.add(jLabel9, gridBagConstraints);

        pzasGalleta.setText("39");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 23, 11, 0);
        jPanel5.add(pzasGalleta, gridBagConstraints);

        addGalleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Add.png"))); // NOI18N
        addGalleta.setText("Añadir");
        addGalleta.setContentAreaFilled(false);
        addGalleta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addGalleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGalletaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 23, 0, 10);
        jPanel5.add(addGalleta, gridBagConstraints);

        jLabel18.setText("pzas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 18, 11, 0);
        jPanel5.add(jLabel18, gridBagConstraints);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(199, 88));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        jLabel11.setText("Pay");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 23, 0, 0);
        jPanel6.add(jLabel11, gridBagConstraints);

        pzasPay.setText("7");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 23, 11, 0);
        jPanel6.add(pzasPay, gridBagConstraints);

        addPay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Add.png"))); // NOI18N
        addPay.setText("Añadir");
        addPay.setContentAreaFilled(false);
        addPay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPayActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 25, 0, 10);
        jPanel6.add(addPay, gridBagConstraints);

        jLabel19.setText("pzas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 12, 11, 0);
        jPanel6.add(jLabel19, gridBagConstraints);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jLabel13.setText("Pastel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 23, 0, 0);
        jPanel7.add(jLabel13, gridBagConstraints);

        pzasPastel.setText("12");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 23, 11, 0);
        jPanel7.add(pzasPastel, gridBagConstraints);

        addPastel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Add.png"))); // NOI18N
        addPastel.setText("Añadir");
        addPastel.setContentAreaFilled(false);
        addPastel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addPastel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPastelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 23, 0, 10);
        jPanel7.add(addPastel, gridBagConstraints);

        jLabel21.setText("pzas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 1, 11, 0);
        jPanel7.add(jLabel21, gridBagConstraints);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new java.awt.GridBagLayout());

        jLabel15.setText("Helado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 23, 0, 0);
        jPanel8.add(jLabel15, gridBagConstraints);

        pzasHelado.setText("21");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 23, 11, 0);
        jPanel8.add(pzasHelado, gridBagConstraints);

        addHelado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Add.png"))); // NOI18N
        addHelado.setText("Añadir");
        addHelado.setContentAreaFilled(false);
        addHelado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addHelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHeladoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 23, 0, 10);
        jPanel8.add(addHelado, gridBagConstraints);

        jLabel20.setText("pzas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 18, 11, 0);
        jPanel8.add(jLabel20, gridBagConstraints);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Return.png"))); // NOI18N
        back.setContentAreaFilled(false);
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ReturnGrande.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new java.awt.GridBagLayout());

        txt2.setText("Muffin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 23, 0, 0);
        jPanel9.add(txt2, gridBagConstraints);

        pzasMuffin.setText("10");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 23, 11, 0);
        jPanel9.add(pzasMuffin, gridBagConstraints);

        addMuffin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Add.png"))); // NOI18N
        addMuffin.setText("Añadir");
        addMuffin.setContentAreaFilled(false);
        addMuffin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addMuffin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMuffinActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 23, 0, 10);
        jPanel9.add(addMuffin, gridBagConstraints);

        jLabel8.setText("pzas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 7, 11, 0);
        jPanel9.add(jLabel8, gridBagConstraints);

        javax.swing.GroupLayout invPanelLayout = new javax.swing.GroupLayout(invPanel);
        invPanel.setLayout(invPanelLayout);
        invPanelLayout.setHorizontalGroup(
            invPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, invPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(invPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, invPanelLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, invPanelLayout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(invPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(52, 52, 52)
                .addGroup(invPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(invPanelLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(invPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(40, 40, 40))
            .addGroup(invPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(invPanelLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(541, Short.MAX_VALUE)))
        );
        invPanelLayout.setVerticalGroup(
            invPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(invPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(invPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(invPanelLayout.createSequentialGroup()
                        .addGroup(invPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(invPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(39, 39, 39)
                        .addGroup(invPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))))
            .addGroup(invPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(invPanelLayout.createSequentialGroup()
                    .addGap(139, 139, 139)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(221, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(inv))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 11, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(invPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outActionPerformed
        // REDIRECCIONA A LA PANTALLA LOGIN Y CIERRA LA ACTUAL
        Login log = new Login();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_outActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // REDIRECCIONA A LA PANTALLA HOME Y CIERRA LA ACTUAL
        Home home = new Home();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void addMuffinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMuffinActionPerformed
        /* AGREGA MAS INGREDIENTES AL INVENTARIO (convierte String a int para hacer la suma y despues lo
                                                  convierte a String para mostrarlo en el label) */
        String piezas = pzasMuffin.getText();
        int num = Integer.parseInt(piezas);
        int n = Integer.parseInt(JOptionPane.showInputDialog("Ingresa cantidad"));
        int sum = num + n;
        String sumTxt = sum + "";
        pzasMuffin.setText(sumTxt);
        // LLAMA METODO PARA ACTUALIZAR LA CANTIDAD DISPONIBLE AL AGREGAR INVENTARIO EN LA BASE DE DATOS
        int idAdd = 8;
        agregar(idAdd, sumTxt);
    }//GEN-LAST:event_addMuffinActionPerformed

    private void addCafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCafeActionPerformed
        /* AGREGA MAS INGREDIENTES AL INVENTARIO (convierte String a int para hacer la suma y despues lo
                                                  convierte a String para mostrarlo en el label) */
        String piezas = pzasCafe.getText();
        int num = Integer.parseInt(piezas);
        int n = Integer.parseInt(JOptionPane.showInputDialog("Ingresa cantidad"));
        int sum = num + n;
        String sumTxt = sum + "";
        pzasCafe.setText(sumTxt);
        // LLAMA METODO PARA ACTUALIZAR LA CANTIDAD DISPONIBLE AL AGREGAR INVENTARIO EN LA BASE DE DATOS
        int idAdd = 1;
        agregar(idAdd, sumTxt);
    }//GEN-LAST:event_addCafeActionPerformed

    private void addAzucarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAzucarActionPerformed
        /* AGREGA MAS INGREDIENTES AL INVENTARIO (convierte String a int para hacer la suma y despues lo
                                                  convierte a String para mostrarlo en el label) */
        String piezas = pzasAzucar.getText();
        int num = Integer.parseInt(piezas);
        int n = Integer.parseInt(JOptionPane.showInputDialog("Ingresa cantidad"));
        int sum = num + n;
        String sumTxt = sum + "";
        pzasAzucar.setText(sumTxt);
        // LLAMA METODO PARA ACTUALIZAR LA CANTIDAD DISPONIBLE AL AGREGAR INVENTARIO EN LA BASE DE DATOS
        int idAdd = 2;
        agregar(idAdd, sumTxt);
    }//GEN-LAST:event_addAzucarActionPerformed

    private void addLecheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLecheActionPerformed
        /* AGREGA MAS INGREDIENTES AL INVENTARIO (convierte String a int para hacer la suma y despues lo
                                                  convierte a String para mostrarlo en el label) */
        String piezas = pzasLeche.getText();
        int num = Integer.parseInt(piezas);
        int n = Integer.parseInt(JOptionPane.showInputDialog("Ingresa cantidad"));
        int sum = num + n;
        String sumTxt = sum + "";
        pzasLeche.setText(sumTxt);
        // LLAMA METODO PARA ACTUALIZAR LA CANTIDAD DISPONIBLE AL AGREGAR INVENTARIO EN LA BASE DE DATOS
        int idAdd = 3;
        agregar(idAdd, sumTxt);
    }//GEN-LAST:event_addLecheActionPerformed

    private void addGalletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGalletaActionPerformed
        /* AGREGA MAS INGREDIENTES AL INVENTARIO (convierte String a int para hacer la suma y despues lo
                                                  convierte a String para mostrarlo en el label) */
        String piezas = pzasGalleta.getText();
        int num = Integer.parseInt(piezas);
        int n = Integer.parseInt(JOptionPane.showInputDialog("Ingresa cantidad"));
        int sum = num + n;
        String sumTxt = sum + "";
        pzasGalleta.setText(sumTxt);
        // LLAMA METODO PARA ACTUALIZAR LA CANTIDAD DISPONIBLE AL AGREGAR INVENTARIO EN LA BASE DE DATOS
        int idAdd = 4;
        agregar(idAdd, sumTxt);
    }//GEN-LAST:event_addGalletaActionPerformed

    private void addPastelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPastelActionPerformed
        /* AGREGA MAS INGREDIENTES AL INVENTARIO (convierte String a int para hacer la suma y despues lo
                                                  convierte a String para mostrarlo en el label) */
        String piezas = pzasPastel.getText();
        int num = Integer.parseInt(piezas);
        int n = Integer.parseInt(JOptionPane.showInputDialog("Ingresa cantidad"));
        int sum = num + n;
        String sumTxt = sum + "";
        pzasPastel.setText(sumTxt);
        // LLAMA METODO PARA ACTUALIZAR LA CANTIDAD DISPONIBLE AL AGREGAR INVENTARIO EN LA BASE DE DATOS
        int idAdd = 5;
        agregar(idAdd, sumTxt);
    }//GEN-LAST:event_addPastelActionPerformed

    private void addPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPayActionPerformed
        /* AGREGA MAS INGREDIENTES AL INVENTARIO (convierte String a int para hacer la suma y despues lo
                                                  convierte a String para mostrarlo en el label) */
        String piezas = pzasPay.getText();
        int num = Integer.parseInt(piezas);
        int n = Integer.parseInt(JOptionPane.showInputDialog("Ingresa cantidad"));
        int sum = num + n;
        String sumTxt = sum + "";
        pzasPay.setText(sumTxt);
        // LLAMA METODO PARA ACTUALIZAR LA CANTIDAD DISPONIBLE AL AGREGAR INVENTARIO EN LA BASE DE DATOS
        int idAdd = 6;
        agregar(idAdd, sumTxt);
    }//GEN-LAST:event_addPayActionPerformed

    private void addHeladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHeladoActionPerformed
        /* AGREGA MAS INGREDIENTES AL INVENTARIO (convierte String a int para hacer la suma y despues lo
                                                  convierte a String para mostrarlo en el label) */
        String piezas = pzasHelado.getText();
        int num = Integer.parseInt(piezas);
        int n = Integer.parseInt(JOptionPane.showInputDialog("Ingresa cantidad"));
        int sum = num + n;
        String sumTxt = sum + "";
        pzasHelado.setText(sumTxt);
        // LLAMA METODO PARA ACTUALIZAR LA CANTIDAD DISPONIBLE AL AGREGAR INVENTARIO EN LA BASE DE DATOS
        int idAdd = 7;
        agregar(idAdd, sumTxt);
    }//GEN-LAST:event_addHeladoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAzucar;
    private javax.swing.JButton addCafe;
    private javax.swing.JButton addGalleta;
    private javax.swing.JButton addHelado;
    private javax.swing.JButton addLeche;
    private javax.swing.JButton addMuffin;
    private javax.swing.JButton addPastel;
    private javax.swing.JButton addPay;
    private javax.swing.JButton back;
    private javax.swing.JLabel inv;
    private javax.swing.JPanel invPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton out;
    private javax.swing.JLabel pzasAzucar;
    private javax.swing.JLabel pzasCafe;
    private javax.swing.JLabel pzasGalleta;
    private javax.swing.JLabel pzasHelado;
    private javax.swing.JLabel pzasLeche;
    private javax.swing.JLabel pzasMuffin;
    private javax.swing.JLabel pzasPastel;
    private javax.swing.JLabel pzasPay;
    private javax.swing.JLabel txt1;
    private javax.swing.JLabel txt2;
    // End of variables declaration//GEN-END:variables
}
